blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/eventure-io/eventure/discussions
    about: Ask questions and discuss ideas with the community
  - name: ğŸ’¡ Ideas
    url: https://github.com/eventure-io/eventure/discussions/categories/ideas
    about: Share your ideas for the project
  - name: ğŸ™‹ Q&A
    url: https://github.com/eventure-io/eventure/discussions/categories/q-a
    about: Ask questions about using Eventure
